name: Run Unit & Integration Tests in Docker

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Start Docker Containers
        run: docker-compose up --build -d

      - name: Run Tests
        run: docker-compose exec test-runner dotnet test --logger "trx;LogFileName=TestResults.xml"

      - name: Stop Containers
        run: docker-compose down

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults/
